
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Uses production Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    restart: unless-stopped