services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # or Dockerfile for production
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped